### ISSUE TITLE
Consider creating an error type

### ISSUE THREAD

**Issue by lpil** [MystPi/conversation#1]
Hello!

Thanks for this library! It's super cool and useful!

Currently all information about why reading a body fails gets discarded. There's no way to know if the error was that there was a network problem, or that the JSON was not the correct format, or that you accidentally called one of these functions twice on the same request.

It would be great if there was an error type so the user can tell what the problem is and how to fix it.

Thanks,
Louis

**Comment by MystPi** [comment]
I would love to add an error type to the `Result`s, but I couldn't find documentation regarding how to determine the reason for the error. I'll probably just have to investigate further.

**Comment by MystPi** [comment]
Completed in 76fe98d.
